<Project Sdk="Microsoft.NET.Sdk"><!--<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>-->


	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.3.6" />
		<PackageReference Include="MassTransit.Redis" Version="8.3.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.13" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
			<!--<PrivateAssets>all</PrivateAssets>-->
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.OpenTelemetry" Version="8.0.6" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.11.0-beta.2" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.11.0-beta.2" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
		<PackageReference Include="Scrutor" Version="6.0.1" />

		<PackageReference Include="Npgsql" Version="8.0.6" />

	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Evently.Common.Application\Evently.Common.Application.csproj" />
  </ItemGroup>
</Project>
